### ISSUE TITLE
[2회차] 23.12.03 일 - 점심 메뉴 추천

### ISSUE THREAD

**Issue by haero77** [Study-Steady/Mission-Based-CodeReview-Study#2]
- PR: https://github.com/Study-Steady/java-menu/pulls

**Comment by boompatron** [comment]
- [점심 메뉴 추천 코드 리뷰 요청합니다!](https://github.com/Study-Steady/java-menu/pull/7)

**Comment by hyeonji1220** [comment]
[[점심 메뉴 추천] 이현지 미션 제출합니다.](https://github.com/Study-Steady/java-menu/pull/4)

**Comment by soochangoforit** [comment]
[[점심 메뉴 추천] 이수찬 코드 리뷰 요청합니다.](https://github.com/Study-Steady/java-menu/pull/8)

**Comment by jinchiim** [comment]
- PR:  https://github.com/Study-Steady/java-menu/pull/3

**Comment by hyeon0208** [comment]
[[점심 메뉴 추천] 서현준 코드 리뷰 요청합니다. (수정완)](https://github.com/Study-Steady/java-menu/pull/5)

**Comment by haero77** [comment]
- 리뷰 요청합니다!
  - https://github.com/Study-Steady/java-menu/pull/2
