### ISSUE TITLE
[3회차] 23.12.10 일 - 페어매칭관리 애플리케이션

### ISSUE THREAD

**Issue by haero77** [Study-Steady/Mission-Based-CodeReview-Study#3]
- PR: https://github.com/Study-Steady/java-pairmatching-precourse/pulls

**Comment by haero77** [comment]
리뷰 부탁드립니다 :)

- https://github.com/Study-Steady/java-pairmatching-precourse/pull/3

**Comment by hyeonji1220** [comment]
마지막 리뷰가 되겠네요...! 부탁드립니다ㅎㅎ
https://github.com/Study-Steady/java-pairmatching-precourse/pull/2
